### ISSUE TITLE
Внедрение symfony в Битрикс 

### ISSUE THREAD

**Issue by codebugmail** [webarchitect609/bitrix-iblock-property-type#8]
Добрый день! Не знал как свами связаться. Решил написать сюда)
Видел в сети, в одном из ваших проектов, как вы связали 1С-Битрикс и Symfony.
Подскажите пожалуйста, есть ли примеры, чистой связи Битрикса и Симфони, без бизнес логики проекта ?

Было бы очень полезно, получить от вас информацию, о том, как это работает.
Единственное, понял, что как симфони подключается только в случае, когда нет подходящих роутов в битриксе (в urlrewrite.php), то подключаются роуты симфы (symfony_router.php). 
Но как дальше происходит инициализация ядра симфони, непонятно.

**Comment by webarchitect609** [comment]
Готовых чистых примеров нет. Да и варианты возможны самые разнообразные. Можно, например, не ставить полную Symfony, а установить только несколько компонентов. Другой вариант это установить полную Symfony и взять за основу её структуру папок, а в `web` установить Битрикс.

И с Битриксом тоже можно по-разному соединяться. Можно через Битриксовый роутер, когда не найдено роутов Битрикса, то подключать Symfony. А можно настроить в Nginx или Apache сразу передавать управление Symfony, в обход Битрикса. Тогда можно использовать адмнику Битрикса как интерфейс, а со стороны сайта сделать REST API, которое будет использовать front-end на Vue или Nuxt для отрисовки страниц сайта. А внутри REST API будет дёргаться API Битрикса.

> Но как дальше происходит инициализация ядра симфони, непонятно.

Ядро надо писать кастомное, наследуясь от стандартного абстрактного `\Symfony\Component\HttpKernel\Kernel`, и решать там проблемы совместимости двух систем. Это тоже целая лекция.

Ну а файл обработки запроса через Symfony может, например, выглядеть так

```php
<?php
declare(strict_types = 1);

use Symfony\Component\HttpFoundation\Request;

define('PULL_AJAX_INIT', true);
define('PUBLIC_AJAX_MODE', true);
define('STOP_STATISTICS', true);
define('NO_AGENT_CHECK', true);
define('NOT_CHECK_PERMISSIONS', false);
define('DisableEventsCheck', true);
define('NO_KEEP_STATISTIC', 'Y');
define('NO_AGENT_STATISTIC', 'Y');

require_once $_SERVER['DOCUMENT_ROOT'] . '/bitrix/modules/main/include.php';

Request::setTrustedProxies(['127.0.0.1']);

/** @noinspection PhpUnhandledExceptionInspection */
AppKernel::handleRequest(Request::createFromGlobals());

```

, где

```php
class AppKernel extends Kernel
{
....
/**
 * Handle current request
 *
 * @param Request $request
 *
 * @throws Exception
 */
public static function handleRequest(Request $request): void
{
    $instance = static::getInstance();
    $response = $instance->handle($request);
    $response->send();
    $instance->terminate($request, $response);
}
```
и в такой версии ядро Symfony приходится делать синглтоном.
